# Minimal Chirpy configuration
title: "野兔很笨"
url: "https://lwkjob.github.io"
theme: jekyll-theme-chirpy
lang: zh-CN
timezone: Asia/Shanghai

social:
  name: 李文科

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post