# Site settings
title: "李文科笔记"
description: "野兔的笔记."
keywords: "spring, java, python"
baseurl: ""
url: "http:////www.lwkjob.com"
highlighter: pygments
paginate: 5
author:
    name: lwk
    github: lwkjob
    email: lwkjob@gmail.com
    gitcafe: 
    twitter:
    facebook:
    googleplus:
    weibo: lwkjob
qiniudn: //havee.qiniudn.com                # //{bucket}.qiniudn.com
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

# comment
comments:
    duoshuo:	
        name: lwkjob                           # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid:                             # 百度统计 js 代码后的字符串

# blogroll
blogroll: true
brlist:
    - text: "酷壳-左耳朵耗子"
      url : //coolshell.cn//
    - text: "MacTalk-池建强"
      url : //macshuo.com/
    - text: "阮一峰的网络日志"
      url : //www.ruanyifeng.com/blog/
